# ===============================================
# == Default Configuration File of 'ShopChest' ==
# ===============================================
#
# Lines starting with '#' are comments and are ignored by the server.
#
# If you are using special characters be sure to save this file in ANSI encoding!
#
# Color Codes (Must be BEFORE Formatting Codes):
# &0 = Black
# &1 = Dark Blue
# &2 = Dark Green
# &3 = Dark Aqua
# &4 = Dark Red
# &5 = Dark Purple
# &6 = Gold
# &7 = Gray
# &8 = Dark Gray
# &9 = Blue
# &a = Green
# &b = Aqua
# &c = Red
# &d = Light Purple
# &e = Yellow
# &f = White
#
# Formatting Codes (Must be AFTER Color Codes):
# &k = Obfuscated
# &l = Bold
# &m = Strikethrough
# &n = Underline
# &o = Italic
# &r = Reset
# \n = Extra line

# Set the main command you have to enter to manage the shops (default: "/shop ...")
# DO NOT USE COLOR-/FORMATTING CODES HERE!
main-command-name: "shop"

# Set the maximal distance to the shop where the player can see the hologram.
# Value MUST be a number (e.g. 1, 1.5, 2.75, ...)
maximal-distance: 1.75

# Set whether the shops' chest should be protected by hoppers
hopper-protection: true

# Set whether the shops' chest should be protected by explosions
explosion-protection: true

# Set the currency symbol after price values
currency-symbol: $

# Set whether the buy price must be greater than or equal sell price.
buy-greater-or-equal-sell: true

# Set the minimum prices for each individual Item. Not per Stack, per single Item!
# To add an item DELETE THE '[]' after 'minimum-prices:' and follow the format below.
# Important: You must have exactly 2 spaces between the text and the edge.
# You can find the item names in the 'item_names.txt' file.
minimum-prices: []
#  "STONE:1": 0.5
#  "DIAMOND_SWORD": 100

# Set the items of which a player can't create a shop.
# To add an item DELETE THE '[]' after 'blacklist:' and follow format below.
# Important: You must have exactly 2 spaces between the text and edge.
# You can find the item names in the 'item_names.txt' file. 
blacklist: []
#  - "STONE:1"
#  - "DIAMOND_BLOCK"

# Priority: default < group < player
shop-limits:
  
  # Set the amount of shops anyone who's not listed in the sections below can have.
  # If you don't want the players to have a limit, set the value to -1.
  default: 5
  
  # Set the amount of shops a player in a specific permission group can have.
  # If you don't want the group to have a limit, set the value to -1.
  # To add an item DELETE THE '[]' after 'group:' and follow the format below.
  # Important: You must have exactly 4 spaces between the text and the edge.
  group: []
  #  "VIP": 10

  # Set the amount of shops a specific player can have.
  # You can add a player by its name or by its UUID, but please do NOT provide the name and the UUID.
  # If you don't want the player to have a limit, set the value to -1.
  # To add an item DELETE THE '[]' after 'player:' and follow the format below.
  # Important: You must have exactly 4 spaces between the text and the edge.
  player: []
  #  "EpicEric": 50
  #  "898afbbe-6566-4a0f-b0ac-145868b3cb12": 50

messages:

  # Set the message when a shop is created at the clicked chest.
  shop-created: "&6Shop created."

  # Set the message when the clicked chest already is a shop.
  chest-already-shop: "&cChest already is shop."

  # Set the message when the clicked shop is removed.
  shop-removed: "&6Shop removed."

  # Set the message when the clicked chest is not a shop.
  chest-no-shop: "&cChest is not a shop."

  shop-info:

    # Set the vendor message the player gets after entering '/shop info'.
    # Usable regex: %VENDOR%
    vendor: "&6Vendor: %VENDOR%"

    # Set the product message the player gets after entering '/shop info'.
    # Usable regex: %AMOUNT%, %ITEMNAME%
    product: "&6Product: %AMOUNT% x %ITEMNAME%"

    # Set the in-stock message the player after entering '/shop info'.
    # Usable regex: %AMOUNT%
    stock: "&6In Stock: %AMOUNT%"

    # Set the enchantments message the player gets after entering '/shop info' if the item is enchanted
    # Usable regex: %ENCHANTMENT%
    enchantments: "&6Enchantments: %ENCHANTMENT%"

    # Set the price message the player gets after entering '/shop info'.
    # Usable regex: %BUY-PRICE%, %SELL-PRICE%, %CURRENCY-SYMBOL%
    price: "&6Price: Buy: %BUY-PRICE%%CURRENCY-SYMBOL%, Sell: %SELL-PRICE%%CURRENCY-SYMBOL%"

    # If the sell price or buy price is disabled, this message will be displayed instead of the price and the currency symbol in the message above.
    disabled: "&7Disabled&6"
    
    # Set the infinite message the player gets after entering '/shop info' ...
    # ... when the shop is infinite.
    is-infinite: "&6Type: Infinite"
    
    # ... when the shop is normal.
    is-normal: "&6Type: Normal"
    
    # ... when the shop is an admin shop.
    is-admin: "&6Type: Admin"

  # Set the message when the clicked block is not a chest.
  block-no-chest: "&cBlock is not a chest"

  # Set the message when the player tries to create a shop with sell price and buy price set to 0
  buy-and-sell-disabled: "&cYou can't create a shop with buying and selling disabled."
  
  # Set the message when the player successfully bought something.
  # Usable regex: %AMOUNT%, %ITEMNAME%, %BUY-PRICE%, %CURRENCY-SYMBOL%, %VENDOR%
  buy-success: "&aYou bought &6%AMOUNT% x %ITEMNAME%&a for &6%BUY-PRICE%%CURRENCY-SYMBOL%&a from &6%VENDOR%&a."
  
  # Set the message when the player successfully bought something from an admin shop.
  # Usable regex: %AMOUNT%, %ITEMNAME%, %BUY-PRICE%, %CURRENCY-SYMBOL%
  buy-success-admin: "&aYou bought &6%AMOUNT% x %ITEMNAME%&a for &6%BUY-PRICE%%CURRENCY-SYMBOL%&a."
  
  # Set the message when the player successfully sold something.
  # Usable regex: %AMOUNT%, %ITEMNAME%, %SELL-PRICE%, %CURRENCY-SYMBOL%, %VENDOR%
  sell-success: "&aYou sold &6%AMOUNT% x %ITEMNAME%&a for &6%SELL-PRICE%%CURRENCY-SYMBOL%&a to &6%VENDOR%&a."
  
  # Set the message when the player successfully sold something to an admin shop.
  # Usable regex: %AMOUNT%, %ITEMNAME%, %SELL-PRICE%, %CURRENCY-SYMBOL%
  sell-success-admin: "&aYou sold &6%AMOUNT% x %ITEMNAME%&a for &6%SELL-PRICE%%CURRENCY-SYMBOL%&a."

  # Set the message when a player bought something from the players' shop.
  # Usable regex: %AMOUNT%, %ITEMNAME%, %BUY-PRICE%, %CURRENCY-SYMBOL%, %PLAYER%
  someone-bought: "&6%PLAYER% &abought &6%AMOUNT% x %ITEMNAME%&a for &6%BUY-PRICE%%CURRENCY-SYMBOL%&a from your shop."
  
  # Set the message when a player sold something to the players' shop.
  # Usable regex: %AMOUNT%, %ITEMNAME%, %SELL-PRICE%, %CURRENCY-SYMBOL%, %PLAYER%
  someone-sold: "&6%PLAYER% &asold &6%AMOUNT% x %ITEMNAME%&a for &6%SELL-PRICE%%CURRENCY-SYMBOL%&a from your shop."

  # Set the message when the inventory is full when the player is buying something.
  not-enough-inventory-space: "&cNot enough space in inventory."
  
  # Set the message when the shops' inventory is full when the player is selling something.
  chest-not-enough-inventory-space: "&cShop is full."

  # Set the message when the player doesn't have enough money to buy something.
  not-enough-money: "&cNot enough money."

  # Set the message when the player doesn't have enough items to sell.
  not-enough-items: "&cNot enough items."

  # Set the message when the vendor doesn't have enough money to buy something from the player
  vendor-not-enough-money: "&cVendor has not enough money."

  # Set the message when the shop is out of stock.
  out-of-stock: "&cShop out of stock."

  # Set the message when an error occurred.
  # Usable regex: %ERROR%
  error-occurred: "&cAn error occurred: %ERROR%"

  # Set the message when the arguments <AMOUNT> and <PRICE> of '/shop create' are not a number.
  amount-and-price-not-number: "&cAmount and price must be a number."

  # Set the message when the player doesn't hold an item in the hand.
  no-item-in-hand: "&cNo item in hand"

  # Set the message when the player must click a chest to create a shop.
  click-chest-to-create-shop: "&aClick a chest to create a shop."

  # Set the message when the player must click a shop to remove it.
  click-chest-to-remove-shop: "&aClick a shop-chest to remove the shop."

  # Set the message when the player must click a shop to retrieve information.
  click-chest-for-info: "&aClick a shop to retrieve information."

  # Set the message when the player opened a shop.
  # Usable regex: %VENDOR%
  opened-shop: "&aYou opened %VENDOR%'s shop."

  # Set the message when the player tries to break a shop.
  cannot-break-shop: "&cYou can't break a shop."

  # Set the message when the player tries to sell a broken item.
  cannot-sell-broken-item: "&cYou can't sell a broken item."
  
  # Set the message when the entered buy price is below the minimum price.
  # Usable regex: %MIN-PRICE%, %CURRENCY-SYMBOL%
  buy-price-too-low: "&cThe buy price must be higher than %MIN-PRICE%%CURRENCY-SYMBOL%."
  
  # Set the message when the entered sell price is below the minimum price.
  # Usable regex: %MIN-PRICE%, %CURRENCY-SYMBOL%
  sell-price-too-low: "&cThe sell price must be higher than %MIN-PRICE%%CURRENCY-SYMBOL%."

  # Set the message when buying is disabled at the shop.
  buying-disabled: "&cBuying is disabled at this shop."
  
  # Set the message when selling is disabled at the shop.
  selling-disabled: "&cSelling is disabled at this shop."
  
  # Set the message when reloading is done.
  # Usable regex: %AMOUNT% (Amount of shops)
  reloaded-shops: "&aSuccessfully reloaded %AMOUNT% shop/s."
  
  # Set the message when the players' shop limit is reached.
  # Usable regex: %LIMIT%
  shop-limit-reached: "&cYou reached your limit of &6%LIMIT% &cshop/s."
  
  # Set the message that shows the player how many shop slots of his shop limit he has occupied.
  # Usable regex: %LIMIT%, %AMOUNT% (Amount of shops)
  occupied-shop-slots: "&6You have &c%AMOUNT%/%LIMIT% &6shop slot/s occupied."

  # Set the message when the player tries to create a shop with an item which is listed in the blacklist.
  cannot-sell-item: "&cYou cannot create a shop with this item."

  update:

    # Set the message when an update is available.
    # Usable regex: %VERSION%
    update-available: "&l&6Version &c%VERSION% &6of &cShopChest &6is available &chere."
    
    # Set the message you get when hovering over the available message.
    click-to-download: "Click to download"
    
    # Set the message when no update is available.
    no-update: "&l&6No new update available."
    
    # Set the message when the update checker is started.
    checking: "&l&6Checking for Updates..."
  
  hologram:
  
    # Set the text in the first row of the shops' hologram
    # Usable regex: %ITEMNAME%, %AMOUNT%
    format: "%AMOUNT% * %ITEMNAME%"
  
    # Set the text in the second row of the shops' hologram when the player can buy and sell an item.
    # Usable regex: %BUY-PRICE%, %SELL-PRICE%, %CURRENCY-SYMBOL%
    buy-and-sell: "Buy %BUY-PRICE%%CURRENCY-SYMBOL% | %SELL-PRICE%%CURRENCY-SYMBOL% Sell"
    
    # Set the text in the second row of the shops' hologram when the player can only buy an item.
    # Usable regex: %BUY-PRICE%, %CURRENCY-SYMBOL%
    only-buy: "Buy %BUY-PRICE%%CURRENCY-SYMBOL%"
    
    # Set the text in the second row of the shops' hologram when the player can only sell an item.
    # Usable regex: %SELL-PRICE%, %CURRENCY-SYMBOL%
    only-sell: "Sell %SELL-PRICE%%CURRENCY-SYMBOL%"
    
  no-permission:

    # Set the message when a not permitted player tries to create a shop.
    create: "&cYou don't have permission to create a shop."

    # Set the message when a not permitted player tries to create an infinite shop.
    create-infinite: "&cYou don't have permission to create an infinite shop."

    # Set the message when a not permitted player tries to create an admin shop.
    create-admin: "&cYou don't have permission to create an admin shop."

    # Set the message when a not permitted player tries to open another players' shop.
    open-others: "&cYou don't have permission to open this chest."

    # Set the message when a not permitted player tries to buy something.
    buy: "&cYou don't have permission to buy something."

    # Set the message when a not permitted player tries to sell something.
    sell: "&cYou don't have permission to sell something."

    # Set the message when a not permitted player tries to remove another players' shop.
    remove-others: "&cYou don't have permission to remove this shop."
    
    # Set the message when a not permitted player tries to reload the shops.
    reload: "&cYou don't have permission to reload the shops."
    
    # Set the message when a not permitted player tries to check for updates.
    update: "&cYou don't have permission to check for updates."

    # Set the message when a not permitted player tries to view the shop limits.
    limits: "&cYou don't have permission to view the shop limits."

  command-description:

    # Set the command description message for '/<main-command> create' when you type '/<main-command>'. 
    create: "Create a shop."

    # Set the command description message for '/<main-command> remove' when you type '/<main-command>'. 
    remove: "Remove a shop."

    # Set the command description message for '/<main-command> info' when you type '/<main-command>'. 
    info: "Retrieve shop information."
    
    # Set the command description message for '/<main-command> reload' when you type '/<main-command>'.
    reload: "Reload shops."
    
    # Set the command description message for '/<main-command> update' when you type '/<main-command>'.
    update: "Check for Updates."

    # Set the command description message for '/<main-command> limits' when you type '/<main-command>'.
    limits: "View shop limits."

# End of file.